# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43c887990824b9b517a54a6f31392523b816ed733c4b2f776655c88ff6c0a486fd59ffdcbcdca30f81f9298fc0c4918a2d66d6239aa28af61b30e211575a45da

test:
  secret_key_base: 2b771d1076acaa5f02ea7dc91dd0a26b5663188f77cfeb563f99cafbc648b98dbac51e1ade90b48db9010f4cb16e1c9b4eb87c289ad95b0b70dd529340a47599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
